## ***PyTorch***

#### Tensor Basics

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [4]:
import torch
torch.__version__

'2.1.0+cpu'

In [5]:
import numpy as np

In [8]:
lst = [1, 2, 3, 4]
array = np.array(lst)
array, type(array), array.dtype

(array([1, 2, 3, 4]), numpy.ndarray, dtype('int32'))

#### Convert numpy to PyTorch tensor

In [9]:
tensors = torch.from_numpy(array)
tensors

tensor([1, 2, 3, 4], dtype=torch.int32)

In [17]:
# Indexing
tensors[1:4]

tensor([2, 3, 4], dtype=torch.int32)

In [19]:
# Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[2] = 20
print(f"Tensors : {tensors}")
print(f"Array : {array}")

Tensors : tensor([ 1,  2, 20,  4], dtype=torch.int32)
Array : [ 1  2 20  4]


In [20]:
# Prevent above disadvantage by using torch.tensor
tensor_array = torch.tensor(array)
tensor_array

tensor([ 1,  2, 20,  4], dtype=torch.int32)

In [21]:
tensor_array[3] = 30
print(f"Tensor_Array : {tensor_array}")
print(f"Array : {array}")

Tensor_Array : tensor([ 1,  2, 20, 30], dtype=torch.int32)
Array : [ 1  2 20  4]


In [22]:
# zeros
torch.zeros(2, 3, dtype=torch.float64) # zeros(rows, columns)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [23]:
# ones
torch.ones(3, 3, dtype=torch.float64) # ones(rows, columns)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

#### Arithmetic Operations

In [39]:
a = torch.tensor([4, 5, 5], dtype=torch.float)
b = torch.tensor([5, 6, 9], dtype=torch.float)
print(a + b)

tensor([ 9., 11., 14.])


In [40]:
torch.add(a, b)

tensor([ 9., 11., 14.])

In [42]:
c = torch.zeros(3)

In [43]:
torch.add(a, b, out=c) # Result of add operation is stored in c variable

tensor([ 9., 11., 14.])

In [44]:
c

tensor([ 9., 11., 14.])

In [45]:
torch.add(a, b).sum()

tensor(34.)

#### Dot Product & Mult Operations

In [46]:
x = torch.tensor([4, 5, 6], dtype=torch.float)
y = torch.tensor([5, 7, 5], dtype=torch.float)

In [51]:
print(torch.multiply(x, y))

# (4*5) + (5*7) + (6*5)
print(torch.dot(x, y))

tensor([20., 35., 30.])
tensor(85.)


#### Matrix Multiplication

In [59]:
p = torch.tensor([[3, 4, 1], [3, 4, 2]], dtype=torch.float)
q = torch.tensor([[2, 3], [1, 2], [5, 6]], dtype=torch.float)

In [63]:
# Using different methods
print(torch.matmul(p, q))
print(torch.mm(p, q))
print(p@q)

tensor([[15., 23.],
        [20., 29.]])
tensor([[15., 23.],
        [20., 29.]])
tensor([[15., 23.],
        [20., 29.]])
