## Backpropogation Using PyTorch

In [1]:
import torch

In [2]:
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [3]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [4]:
# Backpropogation y = 2*x // Derivatives of y
y.backward()

In [6]:
print(x.grad)

tensor(8.)


In [7]:
lst = [[2, 3, 1], [4, 5, 2], [2, 5, 3]]
torch_input = torch.tensor(lst, requires_grad=True, dtype=float)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 2.],
        [2., 5., 3.]], dtype=torch.float64, requires_grad=True)

In [9]:
# y = x**3 + x**2
# y = 3*x**2 + 2*x // Derivative of y
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  12.],
        [ 12., 150.,  36.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [11]:
z = y.sum()
z

tensor(490., dtype=torch.float64, grad_fn=<SumBackward0>)

In [12]:
z.backward()

In [13]:
print(torch_input.grad)

tensor([[16., 33.,  5.],
        [56., 85., 16.],
        [16., 85., 33.]], dtype=torch.float64)
